export interface Env {
  SUPABASE_URL: string
  SUPABASE_SECRET_KEY: string
  UPSTASH_REDIS_REST_URL: string
  UPSTASH_REDIS_REST_TOKEN: string
  RATE_LIMIT_REQUESTS?: string
  RATE_LIMIT_WINDOW_SECONDS?: string
}
